import type { NextPage } from "next";
import Head from "next/head";
import { Button, Typography } from "@mui/material";
import { css } from "@emotion/react";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography
        variant="h2"
        css={css`
          font-weight: bold;
          text-align: center;
        `}
      >
        🚧🚧 WIP 🚧🚧
      </Typography>
    </div>
  );
};

export default Home;
