import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "@mui/material";
import { css } from "@emotion/react";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button
        variant="contained"
        css={css`
          margin: 12px;
        `}
      >
        Lorem Ipsum
      </Button>
    </div>
  );
};

export default Home;
